### PR TITLE
ONNX loader for godot 4 mono

### PR DESCRIPTION
**Pull request by yaelatletl**
PR so we can check  if anything's wrong before pushing to main

### CODE REVIEW

**Comment by edbeeching** [comment]
Thanks for the PR. I am having issues getting it to build on linux. 

```
editor/editor_node.cpp:6443 - An EditorPlugin build callback failed.
Copying Godot Offline Packages...
Transient parent has another exclusive child.
```

I will try again tomorrow.

**Comment by edbeeching** [comment]
@yaelatletl I fixed some issues with dotnet and now it works! I think we might need to standardize the input and output names for the networks, but otherwise this is very close to be ready. I will try an export a stablebaselines3 model and get it running.

I have not tried it yet, but what happens if you load this version of the plugin in non c# version of Godot? Also how would we handling adding the csproj file? We let the user select this when they install the plugin?

**Comment by yaelatletl** [comment]
Sorry, I didn't see the first comment, woops. 

I haven't tried that either, though we might need to have the users install the packages or ask them if they need the C# code and then download and install stuff for them.

**Comment by edbeeching** [comment]
@yaelatletl I have got the sb3 onnx export working on the python side. See this PR: https://github.com/edbeeching/godot_rl_agents/pull/101
Next step is to adapt this PR so that it can handle models from rllib and sb3. 

I am thinking the more generic way would be the we pass lists / dicts of the input and output names of the onnx model, either in `RunInference` or `Initialize`. Then we could handle most use cases. What do you think?

**Comment by yaelatletl** [comment]
Could you send me an ONNX generated by sb3 please? So I can start working on adapting it, hopefully it doesn't change a lot

**Comment by edbeeching** [comment]
Sure, the onnx for BallChase is here: https://drive.google.com/file/d/1-SDU7ROwGT0ol1Gkwzcf6-3LnrBA1cPH/view?usp=share_link

It was created with the following example script in the PR:  https://github.com/edbeeching/godot_rl_agents/blob/load_onnx/examples/stable_baselines3_example.py

I made tests to export sb3 models for all the envs, if you need other onnx files that should be a good starting point: https://github.com/edbeeching/godot_rl_agents/blob/load_onnx/tests/test_sb3_onnx_export.py

**Comment by edbeeching** [comment]
Ok, I have updated the export code. Here is the new onnx model for BallChase:
https://drive.google.com/file/d/1-SDU7ROwGT0ol1Gkwzcf6-3LnrBA1cPH/view?usp=share_link

Let me know if you need more changes.

**Comment by yaelatletl** [comment]
Nice, thank you! 
image
It's now the same as the rllib structure, so it should be compatible with the C# loader with no issues

**Comment by edbeeching** [comment]
I loaded the BallChase onnx model in the engine and it worked out of the box with your implementation. Nice work! There are a few more changes to be made in order to make it simple for users to load and run the trained mode, but I think we are good to merge.

**Review by edbeeching — APPROVED** [review]
LGTM!

**Pull request merged**
