### PR TITLE
feat: adding info - is_success

### PR DESCRIPTION
**Pull request by GianiStatie**
Adding the ability to pass game info to the Python code, specifically if a run `is_success`. This gives more info to the developer when a simulation ends and they want to know the outcome.

This MR links to: 
* this Git issue: https://github.com/edbeeching/godot_rl_agents/issues/175

And blocks:
* this other MR: https://github.com/edbeeching/godot_rl_agents/pull/208

### CODE REVIEW

**Comment by Ivan-267** [comment]
image

Got this to work using your Python changes and with some small changes on the plugin side to make this optional. Instead of changing your PR (you might be working on other changes), I will post a PR to your fork when done, so you can check and merge it.

This will also warrant a small tutorial, I will add it.

As expected this can be a very useful feature (in some cases surpassing the reward as the most important metric) even though it's a relatively quick change code-wise. Thanks for working on the issue!

**Comment by GianiStatie** [comment]
You can add to the PR if you want, since this isn’t urgent and I can also push it sometime next week.

**Comment by Ivan-267** [comment]
> You can add to the PR if you want, since this isn’t urgent and I can also push it sometime next week.

OK, I'll add to the PR directly (easier), but and will write when it's done after. The feature is definitely not urgent, and there are some tests I'd like to do - especially for the tutorial part (although that will be a new PR). It seems we might not need to modify the training script - even though the docs suggest adding success to the monitor is needed. It's possible it may be needed in some versions, so I'll make sure to point to that in tutorial.

**Review by Ivan-267 — APPROVED** [review]
Changes should be done, needs a bit more testing.

I mostly made the info optional, removed the reward on reset (as it shouldn't be necessary), and tested/added the tutorial in the other PR (main repository).

Pending review from @edbeeching before merging. If I have some more time to test in the meantime and find any issues (or if anyone else does), feel free to post here.

Great work @GianiStatie

**Review by edbeeching — APPROVED** [review]
LGTM

**Pull request merged**
