### PR TITLE
Chore: Avoid memory leaks on ONNX loader

### PR DESCRIPTION
**Pull request by yaelatletl**
Changes the wrapper to a Resource, and handles properly the deletion of C# disposables.

### CODE REVIEW

**Review by Ivan-267 — CHANGES_REQUESTED** [review]
Hello, first I'd like to thank you for this PR and also for the information you shared with me. I'm still learning about the current implementation and how everything works. 

I would like to contribute proposed changes here that I've made locally after testing this PR to solve some test cases. I'm not sure this is the easiest way to show the proposed changes, but it would likely be unpractical to push as a parallel PR (however let me know if that would be an easier way or if there is another better way to post the proposed changes):

If the game is closed on the exported application on windows (.exe), the `NOTIFICATION_PREDELETE` notification is called in onnx wrapper gd script. However, it is not called with either "Stop" button or "X" button from the editor (at least on my Windows PC). 

After checking the godot documentation on handling quit requests (https://docs.godotengine.org/en/stable/tutorials/inputs/handling_quit_requests.html), in order to keep it a resource and be able to detect "X" of the game from Godot Editor on my system, I added the following lines to sync.gd:

```gdscript
func _notification(what):
	if what == NOTIFICATION_WM_CLOSE_REQUEST or \
	   what == NOTIFICATION_WM_GO_BACK_REQUEST:
		onnx_model.on_close_request()
```

This needs to be added to sync.gd with the current implementation since Resource class doesn't have access to those notifications.

and in ONNX_wrapper.gd I added to line 6:
```gdscript
var disposed : bool = false
```

and modified the last few lines to:

```gdscript
func _notification(what):
	if what == NOTIFICATION_PREDELETE and not disposed:
		inferencer.FreeDisposables()
		inferencer.free()
		disposed = true

func on_close_request():
	if not disposed:
		inferencer.FreeDisposables()
		inferencer.free()
		disposed = true
```

There is some duplication of disposal, but it serves different purposes. The first is called when e.g. switching scene or closing the exported game, but the second is called when closing the game specifically (also from the editor, but only using "X", I haven't found a solution for when the Stop button is pressed yet).

As further improvements to my code the duplicated lines could be added to a separate method if needed (especially if we dispose of more things in the future, it can be refactored), but with the few lines it might not be necessary.

In ONNXInference.cs:

I've added  `results.Dispose();`  before the output is returned, as the results weren't being disposed, this should also take care of output1 and output2 according to my tests (they are marked as disposed after disposing results).

```C#
...
            results.Dispose();
            //Output is a dictionary of arrays, ex: { "output" : [0.1, 0.2, 0.3, 0.4, ...], "state_outs" : [0.5, ...]}
            return output;
        }
...
```

and in this part:
```C#
        /// <include file='docs/ONNXInference.xml' path='docs/members[@name="ONNXInference"]/Load/*'/>
        public InferenceSession LoadModel(string Path)
        {
            Godot.FileAccess file = FileAccess.Open(Path, Godot.FileAccess.ModeFlags.Read);
            byte[] model = file.GetBuffer((int)file.GetLength());
            file.Dispose();
            return new InferenceSession(model, SessionOpt); //Load the model
        }
```

I have locally changed `file.Close()` to `file.Dispose()` as per the Godot documentation (https://docs.godotengine.org/en/stable/classes/class_fileaccess.html#class-fileaccess-method-close):
> In C# the reference must be disposed manually, which can be done with the using statement or by calling the Dispose method directly.

I'm not sure if this is necessary, it's just an optional suggestion based on the docs in case Dispose() does something more than Close() in their C# implementation, e.g. mark the resource as disposed. 

And in SessionConfigurator.cs:

I made some changes locally to fix the application crashing in case of switching scenes (using `get_tree().change_scene_to_file()` which disposes of the nodes and etc.), and then changing back to the scene where the sync node is (which creates the nodes and initializes things again - real-world use case might be with multiple scenes using different onnx models or a high score scene or etc.).

With that code, a new config instance will be made when needed (e.g. the scene switch case). We can also consider reusing the config until the application exists, but this allows the flexibility to change the configuration if needed for each inference session (e.g. the ability to select some options from the Godot inspector in sync node in the future, such as CPU/GPU inference, etc.).

 _Removed the code snippet as it wasn't implemented properly, I've corrected the issues and provided a better implementation in a later message here._

For considering whether we should reuse the loaded model until the application is exited, that can be considered for the future and if implemented we would need to check whether or not we're using the same model or a different one (different scenes might have different models, e.g. one for each level). 

I hope this feedback will be useful and once again thanks for the implementation.

**Comment by yaelatletl** [comment]
Hey, I'm going trough the suggestions, don't worry, in the editor it might seem as if it wasn't proceeding with the notification function, but it is, you just need to run the editor in --verbose to make sure, as most messages printed from the _notification won't show unless you do that. Also, we should still close the file before disposing it

**Comment by yaelatletl** [comment]
.15 ms using dispose, .13 with no dispose, not bad, seems everything's going ok I just gotta check the scene change issue you mentioned

**Comment by Ivan-267** [comment]
Hey, thanks a lot for going through the suggestions and for the additional information.

> In the editor it might seem as if it wasn't proceeding with the notification function, but it is, you just need to run the editor in --verbose to make sure, as most messages printed from the _notification won't show unless you do that.

Thanks! I didn't know this, that should simplify the solution a lot. I will try it. 

> We should still close the file before disposing it

Here is a snippet from the official Godot tutorial example (https://docs.godotengine.org/en/stable/classes/class_fileaccess.html): 
```C#
public string Load()
{
    using var file = FileAccess.Open("user://save_game.dat", FileAccess.ModeFlags.Read);
    string content = file.GetAsText();
    return content;
}
```

Also from the docs for the [Close](https://docs.godotengine.org/en/stable/classes/class_fileaccess.html#method-descriptions) method:
> Note: FileAccess will automatically close when it's freed, which happens when it goes out of scope or when it gets assigned with null. In C# the reference must be disposed after we are done using it, this can be done with the using statement or calling the Dispose method directly.

With the `using` statement applied applied to the LoadModel method, it would look like this:
```C#
        public InferenceSession LoadModel(string Path)
        {
            using Godot.FileAccess file = FileAccess.Open(Path, Godot.FileAccess.ModeFlags.Read);
            byte[] model = file.GetBuffer((int)file.GetLength());
            return new InferenceSession(model, SessionOpt); //Load the model
        }
````
(This calls .Dispose() only, but it seems to be slightly different than manually calling .Dispose(), more information below)



Is the file not getting closed when needed unless .Close() is called? If it is managed properly in this case, perhaps the milliseconds can be reduced without the `.Close()` call in case it is performing some operations twice (I didn't measure the time so I can't be sure).

Visual studio recommends to me to use the using statement instead of .Dispose() (related style rule: https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0063)

While the style is just a design choice usually, in this case it has some functional benefits to use it where possible (sometimes we will have to use .Dispose() manually when calling disposal methods from Godot side). The using block will call dispose in a finalize block, ensuring disposal even in case of exceptions. 

Additional info here (https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/using?redirectedfrom=MSDN): 
> In particular, the using statement ensures that a disposable instance is disposed even if an exception occurs within the block of the using statement. 

And here:
https://stackoverflow.com/a/10984354

Let me know your thoughts on this and whether I can help with testing or implementing some parts. I appreciate your experience and implementations.

**Comment by yaelatletl** [comment]
Alright, I made a last set of changes, used the "using" keyword just once, not for the results as I actually find useful being able to catch any exception and print it out.

**Comment by yaelatletl** [comment]
@Ivan-267 can you check if the crashes are gone? It should be ready to merge now

**Comment by Ivan-267** [comment]
Hello, thank you for these changes. I agree with you regarding using, actually I made an error in the code I provided regarding using for results, it's still possible to use using inside of the try block (corrected the snippet above), but it may not be as convenient to have everything in the try block so we can consider whether we want using later due to its advantages of disposing on error, that shouldn't slow down this PR.

The issue still happens regarding scene switching.

I tried to propose changes in the review, but with multiple line changes, it is difficult to show them line by one and make sure I copy the changes properly, so I made a PR to your fork instead, hopefully that works as a simpler solution:

https://github.com/yaelatletl/godot_rl_agents_plugin/pull/1

As a side-note I also had to disable line 31 in sync.gd while testing scene switching:
```
	#await get_tree().root.ready
```

With that and the above PR, it did pass the test locally with changing scenes and no crashing or errors.

However that part not added to my changes since it may have side effects, I only used it for testing. I would need to check the code more in-depth and spend some time testing different cases before proposing any changes to that part. Perhaps we can look into that more later.

Other than the config disposal/creation suggestions, the PR should now be ready for merging.

**Review by Ivan-267 — APPROVED** [review]
Thanks again for this update.

**Comment by yaelatletl** [comment]
Alright, now it should problem free! Just awaiting aproval from @edbeeching

**Review by edbeeching — APPROVED** [review]
Thanks @yaelatletl and @Ivan-267 for this. LGTM!

**Pull request merged**
